lesson 1
ok-technopolis-2020/Ershov-Vadim pull request #1
Opened 2020-10-12 22:59 UTC by vadim01er

Извиняюсь, я запутался в sublime merge, но уже разобрался. Из-за мешанины я решил пересоздать репозиторий. И еще я изменил то, что вы попросили.

2020-10-13 07:56 UTC, fromanywhere requested changes

2020-10-13 07:56 UTC, fromanywhere commented on TODO.html
> +				<label>All</label>
Лейбл всё еще не слинкован с радикнопкой

2020-10-13 07:56 UTC, fromanywhere commented on TODO.html
> +				<input type="checkbox" name="a" aria-labal="Set as done">
либо приличный name, либо ничего

2020-10-13 16:59 UTC, fromanywhere requested changes

2020-10-13 16:59 UTC, fromanywhere commented on TODO.html
> +					<label>All</label>
Чтобы оно слинковалось, нужен for="all".
Ну или использовать вместо `<div>`-обертки

2020-10-14 16:01 UTC, fromanywhere approved these changes

2020-10-14 16:01 UTC, fromanywhere commented on TODO.html
> +						<input class="item__todo-element" type="checkbox" aria-labal="Completed">
aria-label :)

2020-10-14 20:59 UTC, vadim01er commented on TODO.html
> +						<input class="item__todo-element" type="checkbox" aria-labal="Completed">
Еще там класс написан calss а не class)

2020-10-15 09:16 UTC, fromanywhere commented on TODO.html
> +						<input class="item__todo-element" type="checkbox" aria-labal="Completed">
В общем-то ничего не изменилось — как был aria-labal , так и остался
Разбиение можно не делать, но просто нужно быть готовым доверстать этот стейт, когда понадобится писать редактирование

2020-10-15 19:26 UTC, vadim01er commented on TODO.html
> +						<input class="item__todo-element" type="checkbox" aria-labal="Completed">
А aria-label нужно убрать? Я ему название поменял потому что там было не совсем корректное описание.

2020-10-16 12:42 UTC, fromanywhere commented on TODO.html
> +						<input class="item__todo-element" type="checkbox" aria-labal="Completed">
там опечатка просто

2020-10-16 14:28 UTC, vadim01er commented on TODO.html
> +						<input class="item__todo-element" type="checkbox" aria-labal="Completed">
aaaa понял)

2020-10-16 17:16 UTC, merged